name: Build

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  github-username:
    description: 'GitHub username for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check out package
      uses: actions/checkout@v4
      with:
        # Specify repository so this action can be run from other repositories
        repository: Consent-Management-Platform/consent-api-java-common
        path: consent-api-java-common
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 21
    - name: Run gradle build
      run: gradle wrapper build
      shell: bash
      working-directory: consent-api-java-common
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_USERNAME: ${{ inputs.github-username }}
